set(_CATKIN_CURRENT_PACKAGE "test_MIT")
set(test_MIT_VERSION "0.0.0")
set(test_MIT_MAINTAINER "yu <yu@todo.todo>")
set(test_MIT_PACKAGE_FORMAT "1")
set(test_MIT_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_MIT_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_MIT_BUILDTOOL_DEPENDS "catkin")
set(test_MIT_BUILDTOOL_EXPORT_DEPENDS )
set(test_MIT_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_MIT_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(test_MIT_TEST_DEPENDS )
set(test_MIT_DOC_DEPENDS )
set(test_MIT_DEPRECATED "")